name: PlayerGuard
version: ${project.version}
main: net.nekozouneko.playerguard.PlayerGuard
api-version: '1.13'
folia-supported: true

authors: [Taitaitatata, "Nekozouneko Group"]
depend: [WorldGuard]
softdepend: [Vault]
website: "https://github.com/TeamNekozouneko/PlayerGuard"

commands:
  cancel-claim:
    aliases: [cancel]
    description: "cancel selection"
    usage: "/<command>"
    permission: playerguard.command.cancel
  claim:
    aliases: [hogo]
    description: "Claims selected region"
    usage: "/<command>"
    permission: playerguard.command.claim
  disclaim:
    aliases: [remove-hogo, hogo-remove]
    description: "Claims selected region"
    usage: "/<command>"
    permission: playerguard.command.disclaim
  flags:
    description: "Manages flag of the region"
    usage: "/<command>"
    permission: playerguard.command.flags

  playerguard:
    aliases: [pg, guard]
    description: "PlayerGuard command"
    usage: "/<command> (add|info|remove|transfer) [<args>]"
    permission: playerguard.command.playerguard

  playerguard-admin:
    aliases: [pguard-admin, pg-admin]
    description: "Admin command"
    usage: "/<command> (delete <id>|expand <player> <n>|lookup [<id>]|reload)"
    permission: playerguard.command.admin

permissions:
  playerguard.command.cancel:
    default: true
  playerguard.command.claim:
    default: true
  playerguard.command.disclaim:
    default: true
  playerguard.command.flags:
    default: true
  playerguard.command.playerguard:
    default: true

  playerguard.command.admin:
    children:
      - playerguard.command.admin.delete
      - playerguard.command.admin.expand
      - playerguard.command.admin.lookup
      - playerguard.command.admin.reload
    default: op